# Generated by Django 6.0.5 on 2026-08-25 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REFUND_INITIATED', 'Refund initiated'), ('ORDER_STATUS_CHANGED', 'Order status changed'), ('ORDER_CANCELLED', 'Order cancelled'), ('ORDER_REVERSED', 'Order reversed')], max_length=50)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='common_audi_action_f07e2b_idx'), models.Index(fields=['object_type', 'object_id'], name='common_audi_object__a9d982_idx'), models.Index(fields=['admin', 'created_at'], name='common_audi_admin_i_890df5_idx')],
            },
        ),
    ]
