# Fulfilment Statuses

STATUS_PENDING = "PENDING"
STATUS_PREPARING = "PREPARING"
STATUS_OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
STATUS_DELIVERED = "DELIVERED"
STATUS_CANCELLED = "CANCELLED"

FULFILMENT_STATUS_CHOICES = [
    (STATUS_PENDING, "Pending"),
    (STATUS_PREPARING, "Preparing"),
    (STATUS_OUT_FOR_DELIVERY, "Out for Delivery"),
    (STATUS_DELIVERED, "Delivered"),
    (STATUS_CANCELLED, "Cancelled"),
]


# Payment Statuses

PAYMENT_PENDING = "PENDING"
PAYMENT_PAID = "PAID"
PAYMENT_FAILED = "FAILED"
PAYMENT_REFUNDED = "REFUNDED"

PAYMENT_STATUS_CHOICES = [
    (PAYMENT_PENDING, "Pending"),
    (PAYMENT_PAID, "Paid"),
    (PAYMENT_FAILED, "Failed"),
    (PAYMENT_REFUNDED, "Refunded"),
]


# Delivery Types

DELIVERY = "DELIVERY"
PICKUP = "PICKUP"

DELIVERY_TYPE_CHOICES = [
    (DELIVERY, "Delivery"),
    (PICKUP, "Pickup"),
]