# Generated by Django 6.0.5 on 2026-08-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_guest_address_order_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('DELIVERED', 'Delivered'), ('PICKED_UP', 'Picked Up'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=30),
        ),
    ]
