# Generated by Django 6.0.5 on 2026-09-02 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_delivery_fee_alter_order_subtotal_and_more'),
        ('payments', '0006_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.order'),
        ),
    ]
