# Generated by Django 6.0.5 on 2026-09-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_refund_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='is_cancellation_refund',
            field=models.BooleanField(default=False),
        ),
    ]
