# Generated by Django 6.0.5 on 2026-08-13 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FINALISED', 'Finalised'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('delivery_type', models.CharField(max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('subtotal', models.IntegerField(default=0)),
                ('delivery_fee', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('guest_full_name', models.CharField(blank=True, max_length=255)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.PositiveBigIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('variant_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.checkouttransaction')),
            ],
            options={
                'verbose_name': 'Checkout Transaction Item',
                'verbose_name_plural': 'Checkout Transaction Items',
            },
        ),
        migrations.AddIndex(
            model_name='checkouttransaction',
            index=models.Index(fields=['status', 'expires_at'], name='checkout_ch_status_3333c0_idx'),
        ),
        migrations.AddIndex(
            model_name='checkouttransaction',
            index=models.Index(fields=['user', 'status'], name='checkout_ch_user_id_e3ea23_idx'),
        ),
        migrations.AddIndex(
            model_name='checkouttransaction',
            index=models.Index(fields=['session_id', 'status'], name='checkout_ch_session_a392d5_idx'),
        ),
        migrations.AddIndex(
            model_name='checkouttransaction',
            index=models.Index(fields=['created_at'], name='checkout_ch_created_4eb7c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkouttransactionitem',
            constraint=models.UniqueConstraint(fields=('checkout', 'variant_id'), name='unique_checkout_variant'),
        ),
    ]
