# Generated by Django 6.0.5 on 2026-08-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkouttransaction',
            name='address_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
