# Generated by Django 6.0.5 on 2026-08-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkouttransaction_address_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='checkout.checkouttransaction')),
            ],
            options={
                'indexes': [models.Index(fields=['variant_id', 'expires_at'], name='checkout_st_variant_b8d510_idx'), models.Index(fields=['checkout', 'expires_at'], name='checkout_st_checkou_b16aa2_idx')],
                'constraints': [models.UniqueConstraint(fields=('checkout', 'variant_id'), name='unique_stock_reservation')],
            },
        ),
    ]
