# Generated by Django 6.0.5 on 2026-08-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_stockreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkouttransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
